param([string]$ProjectRoot='', [string]$EvidencePath='')
$ErrorActionPreference='Stop'
if(-not $ProjectRoot){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))}
$importer=Join-Path $ProjectRoot 'deploy\sync-from-runtime.ps1'
$root=Join-Path ([IO.Path]::GetTempPath()) ('antigravity-import-tests-'+[guid]::NewGuid().ToString('N'))
$results=New-Object Collections.Generic.List[object]
function Put($p,$s){New-Item -ItemType Directory -Force -Path (Split-Path -Parent $p)|Out-Null;[IO.File]::WriteAllText($p,$s,(New-Object Text.UTF8Encoding($false)))}
function Assert($ok,$message){if(-not $ok){throw $message}}
function Reject([scriptblock]$body){$no=$false;try{& $body|Out-Null}catch{$no=$true};Assert $no 'Expected safe refusal.'}
function Fixture($name){$r=Join-Path $root $name;$runtime=Join-Path $r 'runtime';$project=Join-Path $r 'project';New-Item -ItemType Directory -Force -Path $runtime,$project|Out-Null;Put (Join-Path $runtime 'AGENTS.md') 'public agents';return @{root=$r;runtime=$runtime;project=$project}}
function Case($name,[scriptblock]$body){try{& $body (Fixture $name);$results.Add(@{name=$name;status='passed'})}catch{$results.Add(@{name=$name;status='failed';reason=$_.Exception.Message})}}
Case 'public-import-positive' {param($f)Put (Join-Path $f.runtime 'scripts\public.ps1') "'safe'";& $importer -GeminiHome $f.runtime -ProjectRoot $f.project|Out-Null;Assert (Test-Path (Join-Path $f.project 'src\scripts\public.ps1')) 'Public script not imported.'}
Case 'root-private-marker-refused-before-refresh' {param($f)Put (Join-Path $f.runtime '.gemini-private') '';Put (Join-Path $f.project 'src\keep.txt') 'keep';Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project -Refresh};Assert (Test-Path (Join-Path $f.project 'src\keep.txt')) 'Refresh moved files before root admission.'}
Case 'private-ancestor-root-refused' {param($f)Put (Join-Path $f.root '.gemini-private') '';Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project};Assert (-not(Test-Path (Join-Path $f.project 'src'))) 'Private ancestor was ignored.'}
Case 'nested-private-subtree-skipped' {param($f)Put (Join-Path $f.runtime 'scripts\private\.gemini-private') '';Put (Join-Path $f.runtime 'scripts\private\nested\secret.ps1') 'PRIVATE_SENTINEL';Put (Join-Path $f.runtime 'scripts\public.ps1') "'safe'";& $importer -GeminiHome $f.runtime -ProjectRoot $f.project|Out-Null;Assert (-not(Test-Path (Join-Path $f.project 'src\scripts\private\nested\secret.ps1'))) 'Private nested script leaked.';Assert (Test-Path (Join-Path $f.project 'src\scripts\public.ps1')) 'Public sibling was lost.'}
Case 'source-junction-refused' {param($f)$outside=Join-Path $f.root 'outside';Put (Join-Path $outside 'leak.ps1') 'PRIVATE_SENTINEL';New-Item -ItemType Junction -Path (Join-Path $f.runtime 'scripts') -Target $outside|Out-Null;Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project};Assert (-not(Test-Path (Join-Path $f.project 'src\scripts\leak.ps1'))) 'Source junction traversed.'}
Case 'source-ads-refused-before-copy' {param($f)$p=Join-Path $f.runtime 'AGENTS.md';Set-Content -LiteralPath $p -Stream hidden -Value 'PRIVATE_SENTINEL';Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project};Assert (-not(Test-Path (Join-Path $f.project 'src\AGENTS.md'))) 'ADS source copied before refusal.'}
Case 'source-hardlink-refused' {param($f)$outside=Join-Path $f.root 'private-original.ps1';Put $outside 'PRIVATE_SENTINEL';New-Item -ItemType Directory -Path (Join-Path $f.runtime 'scripts')|Out-Null;New-Item -ItemType HardLink -Path (Join-Path $f.runtime 'scripts\alias.ps1') -Target $outside|Out-Null;Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project}}
Case 'destination-junction-refused-before-write' {param($f)$outside=Join-Path $f.root 'outside';New-Item -ItemType Directory -Path $outside|Out-Null;New-Item -ItemType Junction -Path (Join-Path $f.project 'src') -Target $outside|Out-Null;Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project};Assert (-not(Test-Path (Join-Path $outside 'AGENTS.md'))) 'Destination junction was written.'}
Case 'destination-private-subtree-refused-before-copy' {param($f)Put (Join-Path $f.runtime 'scripts\private\p.ps1') "'public'";Put (Join-Path $f.project 'src\scripts\private\.gemini-private') '';Put (Join-Path $f.project 'src\scripts\private\p.ps1') 'PRIVATE_EXISTING';Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project};Assert ((Get-Content -LiteralPath (Join-Path $f.project 'src\scripts\private\p.ps1') -Raw) -eq 'PRIVATE_EXISTING') 'Private destination overwritten.'}
Case 'destination-hardlink-preserved' {param($f)$outside=Join-Path $f.root 'outside.md';Put $outside 'ORIGINAL';New-Item -ItemType Directory -Path (Join-Path $f.project 'src')|Out-Null;New-Item -ItemType HardLink -Path (Join-Path $f.project 'src\AGENTS.md') -Target $outside|Out-Null;Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project};Assert ((Get-Content -LiteralPath $outside -Raw) -eq 'ORIGINAL') 'Destination hardlink overwrote original.'}
Case 'refresh-source-kept-on-unsafe-artifacts' {param($f)Put (Join-Path $f.project 'src\keep.txt') 'keep';$outside=Join-Path $f.root 'outside';New-Item -ItemType Directory -Path $outside|Out-Null;New-Item -ItemType Junction -Path (Join-Path $f.project 'artifacts') -Target $outside|Out-Null;Reject {& $importer -GeminiHome $f.runtime -ProjectRoot $f.project -Refresh};Assert (Test-Path (Join-Path $f.project 'src\keep.txt')) 'Unsafe refresh displaced src.'}
Case 'refresh-retains-safe-prior-source' {param($f)Put (Join-Path $f.project 'src\keep.txt') 'keep';& $importer -GeminiHome $f.runtime -ProjectRoot $f.project -Refresh|Out-Null;Assert (@(Get-ChildItem -LiteralPath (Join-Path $f.project 'artifacts') -Recurse -File -Filter keep.txt).Count -eq 1) 'Refresh prior source not retained.'}
$failed=@($results|Where-Object {$_.status -eq 'failed'}).Count
$report=@{status=if($failed){'failed'}else{'passed'};cases=$results.Count;failed=$failed;results=@($results.ToArray());fixture_root=$root;powershell=$PSVersionTable.PSVersion.ToString();coverage='Focused boundary cases; no live runtime import or measured code coverage.'}
if($EvidencePath){Put $EvidencePath ($report|ConvertTo-Json -Depth 10)}
$report|ConvertTo-Json -Depth 10
if($failed){throw "$failed runtime import cases failed."}
